### PR TITLE
Feature/refactor template info

### PR DESCRIPTION
**Pull request by liuxt805**
Refactor Template Info Page:
1. Remove getTemplate by id API as it doesn't exist
2. Implement TemplateStore to store the current selected template
3. Refactor TemplateApi class and replace some of the functions (e.g. getAccessibleTemplates)
4. Remove mock API for getTemplate by id 
5. Add e2e testing for Template Info Page

### CODE REVIEW

**Comment by XiaochenHou** [comment]
Hi Xintong,
I just checked your e2e tests, I ran into an error when executing your test.
Screenshot 2023-09-07 at 2 02 56 pm
Which corresponds to the following part I guess:
Screenshot 2023-09-07 at 2 03 04 pm
The template selected does not generate the needed parameters, could you have a further look, please?
Except for this issue, everything else looks just fine, thanks.

**Comment by liuxt805** [comment]
fixed, please review again @XiaochenHou

**Review by xiaoranz1 — APPROVED** [review]
After review, there were no issues with the test.

**Comment by XiaochenHou** [comment]
Still cannot get it running, Please fix.
Screenshot 2023-09-10 at 3 18 48 pm

**Comment by liuxt805** [comment]
you run the wrong test file, it should be template_info, please check again, thanks

**Comment by XiaochenHou** [comment]
> Hi @XiaochenHou, you run the wrong test file, it should be template_info, please check again, thanks
My bad, just tested, all good now.

**Review by XiaochenHou — APPROVED** [review]

**Pull request merged**
